version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=property_admin
      - POSTGRES_USER=property_admin
      - POSTGRES_DB=property_db

volumes:
  database_data:
    driver: local